/// Auto-generated by generate_showcase.py — DO NOT EDIT
class LandingAssets {
  LandingAssets._();

  // ── UI backgrounds ──
  static const String heroBg = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/landing-assets/ui/hero-bg.png';
  static const String ctaBg = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/landing-assets/ui/cta-bg.png';
  static const String howStep1 = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/landing-assets/ui/how-step1.png';
  static const String howStep2 = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/landing-assets/ui/how-step2.png';
  static const String howStep3 = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/landing-assets/ui/how-step3.png';

  // ── Showcase story IDs ──
  static const String tale1Id = 'e85f654c-d2d5-44e6-8160-8861bded01c0';
  static const String tale2Id = 'c7d27217-0c83-47a4-abfe-903aafaed86b';
  static const String tale3Id = '1a31734f-350b-4247-8acd-473dd3f2550d';
  static const String tale4Id = '5a24c43f-1822-4d5c-aa14-bbf81016f1da';

  // ── Showcase covers ──
  static const String tale1Cover = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/e85f654c-d2d5-44e6-8160-8861bded01c0/cover.png';
  static const String tale2Cover = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/c7d27217-0c83-47a4-abfe-903aafaed86b/cover.png';
  static const String tale3Cover = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/1a31734f-350b-4247-8acd-473dd3f2550d/cover.png';
  static const String tale4Cover = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/5a24c43f-1822-4d5c-aa14-bbf81016f1da/cover.png';

  // ── Showcase page images (pages 3 and 7) ──
  static const String tale1Page3 = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/e85f654c-d2d5-44e6-8160-8861bded01c0/pages/3.png';
  static const String tale1Page7 = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/e85f654c-d2d5-44e6-8160-8861bded01c0/pages/7.png';
  static const String tale2Page3 = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/c7d27217-0c83-47a4-abfe-903aafaed86b/pages/3.png';
  static const String tale2Page7 = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/c7d27217-0c83-47a4-abfe-903aafaed86b/pages/7.png';
  static const String tale3Page3 = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/1a31734f-350b-4247-8acd-473dd3f2550d/pages/3.png';
  static const String tale3Page7 = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/1a31734f-350b-4247-8acd-473dd3f2550d/pages/7.png';
  static const String tale4Page3 = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/5a24c43f-1822-4d5c-aa14-bbf81016f1da/pages/3.png';
  static const String tale4Page7 = 'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/stories/5a24c43f-1822-4d5c-aa14-bbf81016f1da/pages/7.png';

  // ── Showcase page texts (pages 1, 3, 7) ──
  static const String tale1Text1 = 'Жила-была девочка Маша. Ей было четыре года, и она носила красное пальто с мехом. Однажды мама попросила её принести подснежники из зимнего леса.';
  static const String tale1Text3 = 'Вдруг она увидела костёр и вокруг него двенадцать людей. Это были братья-Месяцы, каждый со своей волшебной силой.';
  static const String tale1Text7 = 'Девочка побежала домой, держа цветы в руках. Лес теперь казался ей волшебным.';
  static const String tale2Text1 = 'Жил-был мальчик Дима. У него были рыжие вихрастые волосы, веснушки и зелёные глаза. Он очень любил играть со своим пушистым серым котом Барсиком.';
  static const String tale2Text3 = 'Когда ракета была готова, она вдруг ожила! Дима и Барсик сели внутрь и полетели в космос.';
  static const String tale2Text7 = 'Дима и Барсик полетели к звезде и нашли, что она просто устала светить. Они её развеселили, и она снова засияла.';
  static const String tale3Text1 = 'В глубоком океане жила маленькая русалочка Алиса. У неё были длинные тёмные волосы и карие глаза. Однажды она заметила, что коралловый дворец стал терять свои яркие краски.';
  static const String tale3Text3 = 'Первым делом они встретили мудрую черепаху Торту. Она рассказала, что волшебные жемчужины помогут вернуть цвета.';
  static const String tale3Text7 = 'Когда они собрали все жемчужины, Алиса вернулась к дворцу. Она разложила их вокруг, и дворец снова засиял яркими красками.';
  static const String tale4Text1 = 'Жил-был мальчик Тимофей. У него были короткие чёрные волосы и смелые тёмные глаза. Однажды он нашёл в шкафу дедушки волшебный плащ.';
  static const String tale4Text3 = 'Сначала Тимофей решил испытать свою суперсилу на улице. Он увидел котёнка, который застрял на дереве. Тимофей взлетел и аккуратно снял котёнка.';
  static const String tale4Text7 = 'Тимофей задумался, что значит быть настоящим супергероем. Он понял, что суперсила — это доброе сердце и помощь другим.';

  // ── Showcase titles ──
  static const String tale1Title = 'Маша и Двенадцать Месяцев';
  static const String tale2Title = 'Дима и Звёздный Кот';
  static const String tale3Title = 'Алиса и Коралловое Королевство';
  static const String tale4Title = 'Супергерой Тимофей';
}
