/// Auto-generated UI asset URLs — do not edit manually.
/// Generated by generate_ui_assets.py
class UiAssets {
  UiAssets._();

  // Worlds
  // Worlds
  static const String magic_forest =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/worlds/magic-forest.png';
  static const String space =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/worlds/space.png';
  static const String underwater =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/worlds/underwater.png';
  static const String medieval_kingdom =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/worlds/medieval-kingdom.png';
  static const String modern_city =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/worlds/modern-city.png';
  static const String dinosaur_world =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/worlds/dinosaur-world.png';

  // Genres
  static const String adventure =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/genres/adventure.png';
  static const String fairy_tale =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/genres/fairy-tale.png';
  static const String educational =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/genres/educational.png';
  static const String friendship =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/genres/friendship.png';
  static const String funny =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/genres/funny.png';
  static const String bedtime =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/genres/bedtime.png';

  // Ages
  static const String age_3_5 =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/ages/age-3-5.png';
  static const String age_6_8 =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/ages/age-6-8.png';
  static const String age_9_12 =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/ages/age-9-12.png';

  // UI
  static const String hero_create_story =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/ui/hero-create-story.png';
  static const String empty_library =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/ui/empty-library.png';
  static const String generation_magic =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/ui/generation-magic.png';
  static const String landing_hero =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/ui/landing-hero.png';
  static const String character_create =
      'https://s3.twcstorage.ru/3e487a89-899c-4ef8-91e2-0900cb899801/ui-assets/ui/character-create.png';

}
